### ISSUE TITLE
Tiny Browser license

### ISSUE THREAD

**Issue by gregshort** [flikQ/rocketeercms#1]
Hi @flikQ 

Just been taking a look through rocketeer, before I use it have a quick question about tinymce.

I see it uses tinybrowser for uploads, which according to http://www.lunarvis.com/products/tinymcefilebrowserwithupload.php/ is a licensed product.

Are we ok to use this as free software in our products etc? Just not sure whether it should be included in this OS software?

Cheers
Greg

**Comment by flikQ** [comment]
Hi Greg,

As far as I am aware it's ok as long as it's not for a commercial product, i.e me selling the CMS. As far as I understand the license you can use this for client work or your own work but not if you wish to sell the CMS as a product a la an Expression Engine type set up.

Client work is ok as the use of the CMS (admin) is in house to the client.

I am not 100% sure but this is my interpretation of the license.

Best,
Gavin

**Comment by flikQ** [comment]
In this comment I was referring to Tiny MCE, not Tiny Browser. Apologies, Tiny Browser has been removed from the Tiny MCE setup.
