### ISSUE TITLE
New user

### ISSUE THREAD

**Issue by crtxz** [flikQ/rocketeercms#3]
When trying to add a new user from admin panel i get the following error:

A PHP Error was encountered

Severity: Notice

Message: Array to string conversion

Filename: mysql/mysql_driver.php

Line Number: 535

A Database Error Occurred
Error Number: 1054

Unknown column 'Array' in 'field list'

**Comment by ucjohn** [comment]
I'm thinking he forgot about this project or he is very busy with his new project aka xfire.. I'm unsure I'm having the same issue also.
